import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  team,
  modal,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='grid grid-cols-1 max-w-7xl mx-auto'>
          {children}
          {/* {team} */}
        </main>
        {modal}
      </body>
    </html>
  );
}
